version: '3'

rpc:
  listen: tcp://127.0.0.1:6001

server:
  command: 'php vendor/bin/rr-worker start'
  relay: pipes

http:
  address: 0.0.0.0:7000
  middleware: [static, gzip]
  static:
    dir: public
    forbid: [".php", ".htaccess"]

