version: '3'

services:
  # PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pos-admin-app
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - pos-network

  # Nginx Service
  webserver:
    image: nginx:alpine
    container_name: pos-admin-webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8030:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - pos-network

  # MySQL Service
  db:
    image: mysql:8
    container_name: pos-admin-db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - pos-network

  # Adminer Service
  adminer:
    image: adminer:4
    container_name: pos-admin-adminer
    restart: unless-stopped
    ports:
      - "8040:8080"
    networks:
      - pos-network

# Networks
networks:
  pos-network:
    driver: bridge

# Volumes
volumes:
  dbdata:
    driver: local
